blank_issues_enabled: false
contact_links:
  - name: Report a security problem privately
    url: https://github.com/CincaAlex/LinkUnzip/security/advisories/new
    about: Please don't post vulnerabilities in public issues.
